import InventoryItemMaster from "../models/InventoryItemMaster.js";
import LocationMaster from "../models/LocationMaster.js";
import SupplierMaster from "../models/SupplierMaster.js";
import CustomerMaster from "../models/CustomerMaster.js";
import InventoryStock from "../models/InventoryStock.js";
import InventoryMovement from "../models/InventoryMovement.js";
import InventoryWorkflow from "../models/InventoryWorkflow.js";
import BOM from "../models/BOM.js";
import Ledger from "../models/Ledger.js";
import Group from "../models/Group.js";
import Voucher from "../models/Voucher.js";
import InventoryCounter from "../models/InventoryCounter.js";
const clean=v=>String(v??"").trim(); const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0}; const r2=v=>Math.round((num(v)+Number.EPSILON)*100)/100;
async function next(key,prefix){const y=new Date().getFullYear();const c=await InventoryCounter.findOneAndUpdate({key:`${key}_${y}`},{$inc:{seq:1}},{upsert:true,new:true,setDefaultsOnInsert:true});return `${prefix}-${y}-${String(c.seq).padStart(5,"0")}`}
async function ledger(name,groupName,nature,req){let l=await Ledger.findOne({name,isActive:true});if(l)return l;let g=await Group.findOne({name:groupName,parent:null});if(!g)g=await Group.create({name:groupName,parent:null,nature,isSystem:true});return Ledger.create({name,group:g._id,createdBy:req.user._id});}
async function voucher(req,date,type,partyLedger,referenceNo,lines,narration,sourceId){const cleanLines=lines.map(x=>({ledger:x.ledger,debit:r2(x.debit),credit:r2(x.credit),narration:x.narration||narration}));const d=r2(cleanLines.reduce((s,x)=>s+x.debit,0)),c=r2(cleanLines.reduce((s,x)=>s+x.credit,0));if(d<=0||Math.abs(d-c)>0.005)throw Error("Accounting voucher is not balanced.");const no=await next("WF_VOUCHER",type.slice(0,3).toUpperCase());return Voucher.create({voucherNo:no,date,type,partyLedger,referenceNo,narration,lines:cleanLines,totalDebit:d,totalCredit:c,sourceType:"INVENTORY_WORKFLOW",sourceId,createdBy:req.user._id})}
export async function getWorkflowMasters(req,res){try{const companyId=req.user?.companyId||null;const [items,locations,suppliers,customers]=await Promise.all([InventoryItemMaster.find({companyId,active:true}).sort({itemType:1,name:1}).lean(),LocationMaster.find({companyId,active:true}).sort({name:1}).lean(),SupplierMaster.find({companyId,active:true}).sort({name:1}).lean(),CustomerMaster.find({companyId,active:true}).sort({name:1}).lean()]);res.json({success:true,items,locations,suppliers,customers})}catch(e){res.status(500).json({success:false,message:e.message})}}
export async function listBoms(req,res){const filter={active:true,companyId:req.user?.companyId||null};res.json({success:true,items:await BOM.find(filter).sort({name:1}).lean()})}
export async function createBom(req,res){try{const b=req.body||{},out=await InventoryItemMaster.findOne({_id:b.outputItemId,companyId:req.user?.companyId||null,active:true});if(!out)throw Error("Output product must be selected from Product Master.");const materials=Array.isArray(b.materials)?b.materials:[];if(!materials.length)throw Error("BOM needs at least one material.");let materialCost=0;const lines=[];for(const x of materials){const item=await InventoryItemMaster.findOne({_id:x.itemId,companyId:req.user?.companyId||null,active:true});if(!item)throw Error("BOM material not found in Product Master.");const qty=num(x.qtyPerUnit);if(qty<=0)throw Error(`Invalid BOM quantity for ${item.name}.`);const rate=num(x.rate);const cost=r2(qty*rate);materialCost+=cost;lines.push({itemId:item._id,itemName:item.name,qtyPerUnit:qty,unit:item.unit,rate,cost})}const labour=Math.max(0,num(b.labourCost)),packing=Math.max(0,num(b.packingCost)),other=Math.max(0,num(b.otherCost)),total=r2(materialCost+labour+packing+other),per=r2(total/(num(b.outputQty)||1));const row=await BOM.findOneAndUpdate({companyId:req.user?.companyId||null,name:clean(b.name)},{companyId:req.user?.companyId||null,name:clean(b.name),outputItemId:out._id,outputItemName:out.name,outputUnit:out.unit,outputQty:num(b.outputQty)||1,materials:lines,labourCost:labour,packingCost:packing,otherCost:other,totalCost:total,costPerUnit:per,active:true,createdBy:req.user._id}, {upsert:true,new:true,setDefaultsOnInsert:true});res.status(201).json({success:true,message:"BOM saved.",item:row})}catch(e){res.status(400).json({success:false,message:e.message})}}
export async function costing(req,res){try{const b=req.body||{},materials=Array.isArray(b.materials)?b.materials:[];const rows=materials.map(x=>({name:clean(x.name),qty:num(x.qty),rate:num(x.rate),cost:r2(num(x.qty)*num(x.rate))}));const material=r2(rows.reduce((s,x)=>s+x.cost,0)),labour=Math.max(0,num(b.labourCost)),packing=Math.max(0,num(b.packingCost)),other=Math.max(0,num(b.otherCost)),total=r2(material+labour+packing+other),outputQty=num(b.outputQty)||1;res.json({success:true,materials:rows,materialCost:material,labourCost:labour,packingCost:packing,otherCost:other,totalCost:total,outputQty,costPerUnit:r2(total/outputQty)})}catch(e){res.status(400).json({success:false,message:e.message})}}
async function stockMove({req,location,line,mode,value,sourceType,sourceNo}){const filter={companyId:req.user?.companyId||null,location,itemType:line.itemType,itemName:line.itemName,batchNo:clean(line.batchNo),barcode:clean(line.barcode)};const old=await InventoryStock.findOne(filter).lean();const oq=num(old?.qty),ov=num(old?.stockValue),q=num(line.qty),v=r2(value);if(mode==="OUT"&&oq<q-0.000001)throw Error(`Insufficient ${line.itemType} stock for ${line.itemName}. Available ${oq}, required ${q}.`);const nq=r2(mode==="OUT"?oq-q:oq+q),nv=r2(Math.max(0,mode==="OUT"?ov-v:ov+v));await InventoryStock.findOneAndUpdate(filter,{$set:{unit:clean(line.unit)||"KG",averageRate:nq?r2(nv/nq):0},$inc:{qty:mode==="OUT"?-q:q,stockValue:mode==="OUT"?-v:v},$setOnInsert:{companyId:req.user?.companyId||null,location,itemType:line.itemType,itemName:line.itemName,batchNo:clean(line.batchNo),barcode:clean(line.barcode)}},{upsert:true,new:true});await InventoryMovement.create({companyId:req.user?.companyId||null,date:new Date(),location,itemName:line.itemName,itemType:line.itemType,unit:line.unit||"KG",qtyIn:mode==="IN"?q:0,qtyOut:mode==="OUT"?q:0,valueIn:mode==="IN"?v:0,valueOut:mode==="OUT"?v:0,balanceQty:nq,sourceType,sourceNo,batchNo:clean(line.batchNo),barcode:clean(line.barcode),createdBy:req.user?._id});return nq}
export async function createPI(req,res){try{const b=req.body||{},customer=await CustomerMaster.findOne({_id:b.partyId,companyId:req.user?.companyId||null,active:true});if(!customer)throw Error("Customer / Party must come from Customer Master.");const lines=(Array.isArray(b.lines)?b.lines:[]).map(x=>({itemId:x.itemId,itemName:clean(x.itemName),itemType:clean(x.itemType)||"FINISHED_GOODS",unit:clean(x.unit)||"KG",qty:num(x.qty),rate:num(x.rate),value:r2(num(x.qty)*num(x.rate)),batchNo:clean(x.batchNo),barcode:clean(x.barcode)}));if(!lines.length||lines.some(x=>!x.itemName||x.qty<=0))throw Error("PI needs valid product lines.");const total=r2(lines.reduce((s,x)=>s+x.value,0)),no=await next("PI","PI");const row=await InventoryWorkflow.create({companyId:req.user?.companyId||null,docNo:no,docType:"PI",date:new Date(b.date||Date.now()),location:clean(b.location),partyId:customer._id,partyName:customer.name,sourceLines:lines,totalValue:total,referenceNo:clean(b.referenceNo),notes:clean(b.notes),createdBy:req.user._id});res.status(201).json({success:true,message:`PI ${no} saved. No stock has been reduced.`,item:row})}catch(e){res.status(400).json({success:false,message:e.message})}}
export async function createReturn(req,res){try{const b=req.body||{},type=clean(b.docType),lines=Array.isArray(b.lines)?b.lines:[],location=clean(b.location);if(!["PURCHASE_RETURN","SALE_RETURN","QUALITY_RETURN","EXPIRED_RETURN"].includes(type)||!location||!lines.length)throw Error("Return type, location and lines are required.");const partyId=b.partyId||null;const party=partyId?(await SupplierMaster.findOne({_id:partyId,companyId:req.user?.companyId||null,active:true}))||(await CustomerMaster.findOne({_id:partyId,companyId:req.user?.companyId||null,active:true})):null;const normalized=lines.map(x=>({...x,itemName:clean(x.itemName),itemType:clean(x.itemType)||"FINISHED_GOODS",unit:clean(x.unit)||"KG",qty:num(x.qty),rate:num(x.rate),value:r2(num(x.qty)*num(x.rate)),batchNo:clean(x.batchNo),barcode:clean(x.barcode)}));if(normalized.some(x=>!x.itemName||x.qty<=0))throw Error("Invalid return line.");const no=await next("RETURN",type==="SALE_RETURN"?"SRN":type==="PURCHASE_RETURN"?"PRN":type==="QUALITY_RETURN"?"QRT":"ERT");const row=await InventoryWorkflow.create({companyId:req.user?.companyId||null,docNo:no,docType:type,date:new Date(b.date||Date.now()),location,partyId:party?._id||null,partyName:party?.name||"",referenceNo:clean(b.referenceNo),sourceLines:normalized,totalValue:r2(normalized.reduce((s,x)=>s+x.value,0)),notes:clean(b.notes),createdBy:req.user._id});for(const x of normalized)await stockMove({req,location,line:x,mode:type==="PURCHASE_RETURN"||type==="QUALITY_RETURN"||type==="EXPIRED_RETURN"?"OUT":"IN",value:x.value,sourceType:type,sourceNo:no});if(party?.ledgerId){const returnLedger=await ledger(type==="SALE_RETURN"?"Sales Return":"Purchase Return",type==="SALE_RETURN"?"Sales Return":"Purchase Return",type==="SALE_RETURN"?"Income":"Expense",req);const linesA=type==="SALE_RETURN"?[{ledger:returnLedger._id,debit:row.totalValue,credit:0},{ledger:party.ledgerId,debit:0,credit:row.totalValue}]:[{ledger:party.ledgerId,debit:row.totalValue,credit:0},{ledger:returnLedger._id,debit:0,credit:row.totalValue}];await voucher(req,row.date,type==="SALE_RETURN"?"Credit Note":"Debit Note",party.ledgerId,no,linesA,`${type} ${no}`,row._id)}res.status(201).json({success:true,message:`${type} ${no} posted with stock and accounts effect.`,item:row})}catch(e){res.status(400).json({success:false,message:e.message})}}
export async function createRepack(req,res){try{const b=req.body||{},location=clean(b.location),sources=Array.isArray(b.sourceLines)?b.sourceLines:[],outputs=Array.isArray(b.outputLines)?b.outputLines:[];if(!location||!sources.length||!outputs.length)throw Error("Location, source and output lines are required.");const no=await next("REPACK","RPK");const row=await InventoryWorkflow.create({companyId:req.user?.companyId||null,docNo:no,docType:"REPACK",date:new Date(b.date||Date.now()),location,sourceLines:sources,outputLines:outputs,notes:clean(b.notes),createdBy:req.user._id});for(const x of sources)await stockMove({req,location,line:{...x,itemType:clean(x.itemType)||"RETURN_GOODS"},mode:"OUT",value:num(x.value)||num(x.qty)*num(x.rate),sourceType:"REPACK",sourceNo:no});for(const x of outputs)await stockMove({req,location,line:{...x,itemType:clean(x.itemType)||"PACKED_GOODS"},mode:"IN",value:num(x.value)||num(x.qty)*num(x.rate),sourceType:"REPACK",sourceNo:no});res.status(201).json({success:true,message:`Repacking ${no} posted.`,item:row})}catch(e){res.status(400).json({success:false,message:e.message})}}
export async function getWorkflowDocs(req,res){try{const filter={companyId:req.user?.companyId||null};if(req.query.docType)filter.docType=clean(req.query.docType);const items=await InventoryWorkflow.find(filter).sort({date:-1,createdAt:-1}).limit(300).lean();res.json({success:true,items})}catch(e){res.status(500).json({success:false,message:e.message})}}
export async function getStockLedger(req,res){try{const filter={companyId:req.user?.companyId||null};if(clean(req.query.location))filter.location=clean(req.query.location);if(clean(req.query.itemName))filter.itemName={$regex:clean(req.query.itemName),$options:"i"};const items=await InventoryMovement.find(filter).sort({date:-1,createdAt:-1}).limit(1000).lean();res.json({success:true,items})}catch(e){res.status(500).json({success:false,message:e.message})}}
