import express from "express";
import auth from "../middleware/auth.js";
import requireRole from "../middleware/role.js";
import {getPurchaseMasters,createLocationMaster,createSupplierMaster,createInventoryItemMaster,createRawMaterialPurchase,getRawMaterialPurchases,getRawMaterialStock,getStock,createJobOrder,getJobs,createSale,getSales,getGstReport} from "../controllers/inventoryController.js";
const router=express.Router();
router.get("/raw-material-masters",auth,getPurchaseMasters);
router.post("/masters/locations",auth,requireRole("Admin","Manager"),createLocationMaster);
router.post("/masters/suppliers",auth,requireRole("Admin","Manager"),createSupplierMaster);
router.post("/masters/items",auth,requireRole("Admin","Manager"),createInventoryItemMaster);
router.get("/raw-material-purchases",auth,getRawMaterialPurchases);
router.post("/raw-material-purchases",auth,requireRole("Admin","Manager"),createRawMaterialPurchase);
router.get("/raw-material-stock",auth,getRawMaterialStock);
router.get("/stock",auth,getStock);
router.post("/job-orders",auth,requireRole("Admin","Manager"),createJobOrder);
router.get("/job-orders",auth,getJobs);
router.post("/sales",auth,requireRole("Admin","Manager"),createSale);
router.get("/sales",auth,getSales);
router.get("/gst-report",auth,getGstReport);
export default router;
