import express from "express";
import auth from "../middleware/auth.js";
import requireRole from "../middleware/role.js";
import {getPurchaseMasters,lookupPincode,lookupGSTIN,createLocationMaster,createSupplierMaster,createInventoryItemMaster,updateLocationMaster,deleteLocationMaster,updateSupplierMaster,deleteSupplierMaster,updateInventoryItemMaster,deleteInventoryItemMaster,createRawMaterialPurchase,getRawMaterialPurchases,getRawMaterialStock,getStock,createJobOrder,getJobs,createSale,getSales,getGstReport} from "../controllers/inventoryController.js";
const router=express.Router();
router.get("/raw-material-masters",auth,getPurchaseMasters);
router.get("/masters/pincode/:pin",auth,lookupPincode);
router.get("/masters/gstin/:gstin",auth,lookupGSTIN);
router.post("/masters/locations",auth,requireRole("Admin","Manager"),createLocationMaster);
router.post("/masters/suppliers",auth,requireRole("Admin","Manager"),createSupplierMaster);
router.post("/masters/items",auth,requireRole("Admin","Manager"),createInventoryItemMaster);
router.put("/masters/locations/:id",auth,requireRole("Admin","Manager"),updateLocationMaster);
router.delete("/masters/locations/:id",auth,requireRole("Admin","Manager"),deleteLocationMaster);
router.put("/masters/suppliers/:id",auth,requireRole("Admin","Manager"),updateSupplierMaster);
router.delete("/masters/suppliers/:id",auth,requireRole("Admin","Manager"),deleteSupplierMaster);
router.put("/masters/items/:id",auth,requireRole("Admin","Manager"),updateInventoryItemMaster);
router.delete("/masters/items/:id",auth,requireRole("Admin","Manager"),deleteInventoryItemMaster);
router.get("/raw-material-purchases",auth,getRawMaterialPurchases);
router.post("/raw-material-purchases",auth,requireRole("Admin","Manager"),createRawMaterialPurchase);
router.get("/raw-material-stock",auth,getRawMaterialStock);
router.get("/stock",auth,getStock);
router.post("/job-orders",auth,requireRole("Admin","Manager"),createJobOrder);
router.get("/job-orders",auth,getJobs);
router.post("/sales",auth,requireRole("Admin","Manager"),createSale);
router.get("/sales",auth,getSales);
router.get("/gst-report",auth,getGstReport);
export default router;
