import express from "express";
import {getWorkflowMasters,listBoms,createBom,costing,createPI,createReturn,createRepack,createDamage,createPackingConversion,getWorkflowDocs,getStockLedger} from "../controllers/inventoryWorkflowController.js";
import auth from "../middleware/auth.js";
import requireRole from "../middleware/role.js";
import {getPurchaseMasters,lookupPincode,lookupGSTIN,createLocationMaster,createSupplierMaster,createCustomerMaster,createInventoryItemMaster,updateLocationMaster,deleteLocationMaster,updateSupplierMaster,deleteSupplierMaster,updateCustomerMaster,deleteCustomerMaster,updateInventoryItemMaster,deleteInventoryItemMaster,createUnitMaster,updateUnitMaster,deleteUnitMaster,createRawMaterialPurchase,getRawMaterialPurchases,getRawMaterialStock,getStock,createJobOrder,getJobs,createSale,getSales,getGstReport} from "../controllers/inventoryController.js";
const router=express.Router();
router.get("/raw-material-masters",auth,getPurchaseMasters);
router.get("/masters/pincode/:pin",auth,lookupPincode);
router.get("/masters/gstin/:gstin",auth,lookupGSTIN);
router.post("/masters/locations",auth,requireRole("Admin","Manager"),createLocationMaster);
router.post("/masters/suppliers",auth,requireRole("Admin","Manager"),createSupplierMaster);
router.post("/masters/customers",auth,requireRole("Admin","Manager"),createCustomerMaster);
router.put("/masters/customers/:id",auth,requireRole("Admin","Manager"),updateCustomerMaster);
router.delete("/masters/customers/:id",auth,requireRole("Admin","Manager"),deleteCustomerMaster);
router.post("/masters/items",auth,requireRole("Admin","Manager"),createInventoryItemMaster);
router.put("/masters/locations/:id",auth,requireRole("Admin","Manager"),updateLocationMaster);
router.delete("/masters/locations/:id",auth,requireRole("Admin","Manager"),deleteLocationMaster);
router.put("/masters/suppliers/:id",auth,requireRole("Admin","Manager"),updateSupplierMaster);
router.delete("/masters/suppliers/:id",auth,requireRole("Admin","Manager"),deleteSupplierMaster);
router.put("/masters/items/:id",auth,requireRole("Admin","Manager"),updateInventoryItemMaster);
router.delete("/masters/items/:id",auth,requireRole("Admin","Manager"),deleteInventoryItemMaster);
router.post("/masters/units",auth,requireRole("Admin","Manager"),createUnitMaster);
router.put("/masters/units/:id",auth,requireRole("Admin","Manager"),updateUnitMaster);
router.delete("/masters/units/:id",auth,requireRole("Admin","Manager"),deleteUnitMaster);
router.get("/raw-material-purchases",auth,getRawMaterialPurchases);
router.post("/raw-material-purchases",auth,requireRole("Admin","Manager"),createRawMaterialPurchase);
router.get("/raw-material-stock",auth,getRawMaterialStock);
router.get("/stock",auth,getStock);
router.post("/job-orders",auth,requireRole("Admin","Manager"),createJobOrder);
router.get("/job-orders",auth,getJobs);
router.post("/sales",auth,requireRole("Admin","Manager"),createSale);
router.get("/sales",auth,getSales);
router.get("/gst-report",auth,getGstReport);
router.get("/workflow/masters",auth,getWorkflowMasters);
router.get("/workflow/boms",auth,listBoms);
router.post("/workflow/boms",auth,requireRole("Admin","Manager"),createBom);
router.post("/workflow/costing",auth,costing);
router.post("/workflow/pi",auth,requireRole("Admin","Manager"),createPI);
router.post("/workflow/returns",auth,requireRole("Admin","Manager"),createReturn);
router.post("/workflow/repack",auth,requireRole("Admin","Manager"),createRepack);
router.post("/workflow/damage",auth,requireRole("Admin","Manager"),createDamage);
router.post("/workflow/packing-conversion",auth,requireRole("Admin","Manager"),createPackingConversion);
router.get("/workflow/documents",auth,getWorkflowDocs);
router.get("/workflow/stock-ledger",auth,getStockLedger);
export default router;
