import React,{useEffect,useState} from "react";
import {hrApi} from "../lib/hrApi.js";

export default function Attendance(){
 const [employees,setEmployees]=useState([]),[rows,setRows]=useState([]),[form,setForm]=useState({employeeId:"",date:new Date().toISOString().slice(0,10),status:"Present",checkIn:"",checkOut:"",overtimeHours:0}),[error,setError]=useState("");
 async function load(){try{const[e,a]=await Promise.all([hrApi.employees(),hrApi.attendance()]);setEmployees(e.employees||[]);setRows(a.attendance||[]);if(!form.employeeId&&e.employees?.[0])setForm(f=>({...f,employeeId:e.employees[0]._id}))}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();try{await hrApi.saveAttendance({...form,overtimeHours:Number(form.overtimeHours||0)});load()}catch(e){setError(e.message)}}
 return <main style={S.page}><h1>Attendance</h1><p style={S.sub}>Daily attendance, check-in/out and overtime</p>{error&&<p style={S.error}>{error}</p>}
 <form onSubmit={save} style={S.card}><select style={S.input} value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}>{employees.map(x=><option key={x._id} value={x._id}>{x.employeeCode} — {x.name}</option>)}</select><input type="date" style={S.input} value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><select style={S.input} value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{["Present","Absent","Half Day","Leave","Holiday","Week Off"].map(x=><option key={x}>{x}</option>)}</select><input placeholder="Check in" style={S.input} value={form.checkIn} onChange={e=>setForm({...form,checkIn:e.target.value})}/><input placeholder="Check out" style={S.input} value={form.checkOut} onChange={e=>setForm({...form,checkOut:e.target.value})}/><input type="number" min="0" step=".5" placeholder="OT hours" style={S.input} value={form.overtimeHours} onChange={e=>setForm({...form,overtimeHours:e.target.value})}/><button style={S.btn}>Save Attendance</button></form>
 <section style={S.card}>{rows.map(a=><div key={a._id} style={S.row}><b>{a.employeeId?.name}</b><span>{new Date(a.date).toLocaleDateString("en-IN")}</span><span style={S.badge}>{a.status}</span><span>{a.checkIn||"--"} → {a.checkOut||"--"}</span><span>OT {a.overtimeHours||0}h</span></div>)}</section></main>
}
const S={page:{padding:24,background:"#f5f7fb",minHeight:"100vh",fontFamily:"Arial"},sub:{color:"#667085"},card:{background:"#fff",padding:20,borderRadius:18,marginTop:18,boxShadow:"0 8px 24px rgba(15,23,42,.06)"},input:{padding:12,border:"1px solid #d9e1ec",borderRadius:10,margin:5},btn:{padding:"12px 18px",background:"#1d4f91",color:"#fff",border:0,borderRadius:10,fontWeight:700},row:{display:"grid",gridTemplateColumns:"1.4fr 1fr .8fr 1.2fr .7fr",gap:10,padding:"13px 0",borderBottom:"1px solid #eee"},badge:{padding:"5px 9px",borderRadius:20,background:"#edf4ff",color:"#1d4f91",fontSize:12},error:{background:"#fee4e2",color:"#b42318",padding:10,borderRadius:10}};
