import React,{useEffect,useMemo,useState} from "react";
const API=(import.meta.env.VITE_API_URL||"https://office-management-system-ikx8.onrender.com").replace(/\/+$/,'');
const H=()=>({"Content-Type":"application/json",Authorization:`Bearer ${localStorage.getItem("token")||localStorage.getItem("accessToken")||""}`});
const n=v=>Number(v)||0; const money=v=>n(v).toFixed(2); const today=()=>new Date().toISOString().slice(0,10);
function Select({value,onChange,children}){return <select value={value||""} onChange={onChange}>{children}</select>}
export default function IntegratedOperations(){
 const [tab,setTab]=useState(()=>new URLSearchParams(window.location.search).get("tab")||"flow"),[m,setM]=useState({items:[],locations:[],suppliers:[],customers:[]}),[boms,setBoms]=useState([]),[docs,setDocs]=useState([]),[ledger,setLedger]=useState([]),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false);
 const [bom,setBom]=useState({name:"",outputItemId:"",outputQty:1,labourCost:0,packingCost:0,otherCost:0,materials:[]});
 const [pi,setPi]=useState({partyId:"",location:"",date:new Date().toISOString().slice(0,10),referenceNo:"",lines:[],notes:""});
 const [ret,setRet]=useState({docType:"SALE_RETURN",partyId:"",location:"",referenceNo:"",lines:[],notes:""});
 const [damage,setDamage]=useState({date:today(),location:"",lines:[],notes:""});
 const [pc,setPc]=useState({date:today(),location:"",sourceLines:[],outputLines:[],conversionCharge:"",notes:""});
 const [repack,setRepack]=useState({location:"",sourceLines:[],outputLines:[],notes:""});
 const [cost,setCost]=useState({outputQty:1,labourCost:0,packingCost:0,otherCost:0,materials:[]}); const [costResult,setCostResult]=useState(null);
 async function get(url){const r=await fetch(API+url,{headers:H()});const d=await r.json();if(!r.ok)throw Error(d.message||"Load failed");return d}
 async function post(url,body){const r=await fetch(API+url,{method:"POST",headers:H(),body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.message||"Save failed");return d}
 async function load(){try{const [a,b,c,d]=await Promise.all([get("/api/inventory/workflow/masters"),get("/api/inventory/workflow/boms"),get("/api/inventory/workflow/documents"),get("/api/inventory/workflow/stock-ledger")]);setM(a);setBoms(b.items||[]);setDocs(c.items||[]);setLedger(d.items||[])}catch(e){setErr(e.message)}}
 useEffect(()=>{load()},[]);
 const products=useMemo(()=>m.items||[],[m.items]);
 const outputProducts=products.filter(x=>["GRADE","FINISHED_GOODS","PACKED_GOODS","RETURN_GOODS"].includes(x.itemType));
 const inputProducts=products.filter(x=>["RAW_MATERIAL","GRADE","FINISHED_GOODS","PACKED_GOODS","RETURN_GOODS"].includes(x.itemType));
 function addLine(setter,field,defaults){setter(x=>({...x,[field]:[...(x[field]||[]),defaults]}))}
 async function save(url,body,done){setBusy(true);setErr("");setMsg("");try{const d=await post(url,body);setMsg(d.message||"Saved successfully");done?.();await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 const addBomMaterial=()=>addLine(setBom,"materials",{itemId:"",qtyPerUnit:1,rate:0});
 const addPiLine=()=>addLine(setPi,"lines",{itemId:"",itemName:"",itemType:"FINISHED_GOODS",unit:"KG",qty:1,rate:0,batchNo:"",barcode:""});
 const addRetLine=()=>addLine(setRet,"lines",{itemId:"",itemName:"",itemType:"FINISHED_GOODS",unit:"KG",qty:1,rate:0,batchNo:"",barcode:""});
 const addSource=()=>addLine(setRepack,"sourceLines",{itemName:"",itemType:"RETURN_GOODS",unit:"KG",qty:1,rate:0}); const addOutput=()=>addLine(setRepack,"outputLines",{itemName:"",itemType:"PACKED_GOODS",unit:"KG",qty:1,rate:0});
 const addCost=()=>addLine(setCost,"materials",{name:"",qty:1,rate:0});
 return <div className="io-page"><style>{`.io-page{padding:22px;max-width:1500px;margin:auto;background:#f6f8fb;min-height:100vh;font-family:Arial}.io-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.io-head h1{margin:0;color:#172b4d}.io-sub{color:#667085;font-size:13px}.io-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.io-tabs button{border:1px solid #d0d5dd;background:#fff;border-radius:9px;padding:9px 13px;cursor:pointer}.io-tabs button.active{background:#175cd3;color:#fff;border-color:#175cd3}.io-card{background:#fff;border:1px solid #eaecf0;border-radius:14px;padding:18px;margin-bottom:15px;box-shadow:0 3px 12px #00000008}.io-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.io-grid .wide{grid-column:span 2}.io-page input,.io-page select,.io-page textarea{width:100%;box-sizing:border-box;padding:9px;border:1px solid #d0d5dd;border-radius:8px;background:#fff}.io-page label{display:block;font-size:12px;color:#475467;margin-bottom:4px}.io-table{width:100%;border-collapse:collapse;min-width:850px}.io-table th,.io-table td{padding:8px;border-bottom:1px solid #eaecf0;text-align:left;font-size:12px}.io-scroll{overflow:auto}.io-btn{border:0;border-radius:8px;padding:9px 13px;cursor:pointer;font-weight:600}.primary{background:#175cd3;color:#fff}.secondary{background:#eef2f6;color:#344054}.danger{background:#fee4e2;color:#b42318}.io-msg{padding:10px;border-radius:8px;background:#ecfdf3;color:#027a48;margin-bottom:12px}.io-err{padding:10px;border-radius:8px;background:#fef3f2;color:#b42318;margin-bottom:12px}.flow{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.step{background:#f8fafc;border:1px solid #e4e7ec;border-radius:12px;padding:14px}.step b{display:block;color:#175cd3;margin-bottom:5px}@media(max-width:900px){.io-grid{grid-template-columns:repeat(2,1fr)}.flow{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.io-grid{grid-template-columns:1fr}.io-grid .wide{grid-column:span 1}.flow{grid-template-columns:1fr}.io-page{padding:12px}}`}</style>
 <div className="io-head"><div><h1>Integrated Inventory & Accounts</h1><div className="io-sub">Purchase → Job Order → Grading → BOM → Costing → PI → Sale → Return → Repacking → Stock → Accounts</div></div><button className="io-btn secondary" onClick={load}>Refresh</button></div>
 <div className="io-tabs">{[["flow","Flow"],["bom","BOM"],["cost","Costing"],["pi","PI"],["return","Returns"],["damage","Damage"],["repack","Repacking"],["packing-conversion","Packing Conversion"],["stock","Stock Ledger"],["docs","Documents"]].map(x=><button className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</div>
 {msg&&<div className="io-msg">✓ {msg}</div>}{err&&<div className="io-err">⚠ {err}</div>}
 {tab==="flow"&&<div className="io-card"><div className="flow">{[["1","Purchase","Raw material stock + Purchase accounts"],["2","Job Order","Consume raw / produce grade"],["3","Grading","Grade-wise stock"],["4","BOM + Costing","Material + labour + packing"],["5","PI","Reserve plan; no stock reduction"],["6","Sale","FG/packed stock out + receivable"],["7","Return","Sale/Purchase/Quality/Expired"],["8","Repacking","Return/loose → packed"],["9","Stock","Movement ledger + balance"],["10","Accounts","Automatic voucher linkage"]].map(x=><div className="step" key={x[0]}><b>{x[0]}. {x[1]}</b><span>{x[2]}</span></div>)}</div><p className="io-sub" style={{marginTop:15}}>Existing Purchase, Job Order, Sale and Accounts screens remain available. This page adds the missing linked workflow without deleting those screens.</p></div>}
 {tab==="bom"&&<><div className="io-card"><h3>Create / Update BOM</h3><div className="io-grid"><div><label>BOM Name</label><input value={bom.name} onChange={e=>setBom({...bom,name:e.target.value})}/></div><div><label>Output Product</label><Select value={bom.outputItemId} onChange={e=>setBom({...bom,outputItemId:e.target.value})}><option value="">Select product</option>{outputProducts.map(x=><option value={x._id} key={x._id}>{x.name} ({x.itemType})</option>)}</Select></div><div><label>Output Qty</label><input type="number" value={bom.outputQty} onChange={e=>setBom({...bom,outputQty:e.target.value})}/></div><div><label>Labour Cost</label><input type="number" value={bom.labourCost} onChange={e=>setBom({...bom,labourCost:e.target.value})}/></div><div><label>Packing Cost</label><input type="number" value={bom.packingCost} onChange={e=>setBom({...bom,packingCost:e.target.value})}/></div><div><label>Other Cost</label><input type="number" value={bom.otherCost} onChange={e=>setBom({...bom,otherCost:e.target.value})}/></div></div><div className="io-scroll"><table className="io-table"><thead><tr><th>Material Master</th><th>Qty / Unit</th><th>Rate</th><th>Cost</th><th></th></tr></thead><tbody>{bom.materials.map((x,i)=><tr key={i}><td><Select value={x.itemId} onChange={e=>setBom(b=>({...b,materials:b.materials.map((v,j)=>j===i?{...v,itemId:e.target.value}:v)}))}><option value="">Select material</option>{inputProducts.map(p=><option value={p._id} key={p._id}>{p.name} ({p.itemType})</option>)}</Select></td><td><input type="number" value={x.qtyPerUnit} onChange={e=>setBom(b=>({...b,materials:b.materials.map((v,j)=>j===i?{...v,qtyPerUnit:e.target.value}:v)}))}/></td><td><input type="number" value={x.rate} onChange={e=>setBom(b=>({...b,materials:b.materials.map((v,j)=>j===i?{...v,rate:e.target.value}:v)}))}/></td><td>₹ {money(n(x.qtyPerUnit)*n(x.rate))}</td><td><button className="io-btn danger" onClick={()=>setBom(b=>({...b,materials:b.materials.filter((_,j)=>j!==i)}))}>×</button></td></tr>)}</tbody></table></div><button className="io-btn secondary" onClick={addBomMaterial}>+ Material</button> <button className="io-btn primary" disabled={busy} onClick={()=>save("/api/inventory/workflow/boms",bom,()=>setBom({name:"",outputItemId:"",outputQty:1,labourCost:0,packingCost:0,otherCost:0,materials:[]}))}>Save BOM</button></div><div className="io-card"><h3>Existing BOM</h3><div className="io-scroll"><table className="io-table"><thead><tr><th>Name</th><th>Output</th><th>Materials</th><th>Total Cost</th><th>Per Unit</th></tr></thead><tbody>{boms.map(x=><tr key={x._id}><td>{x.name}</td><td>{x.outputItemName}</td><td>{x.materials?.length||0}</td><td>₹ {money(x.totalCost)}</td><td>₹ {money(x.costPerUnit)}</td></tr>)}</tbody></table></div></div></>}
 {tab==="cost"&&<div className="io-card"><h3>Product Costing</h3><div className="io-grid"><div><label>Output Qty</label><input type="number" value={cost.outputQty} onChange={e=>setCost({...cost,outputQty:e.target.value})}/></div><div><label>Labour Cost</label><input type="number" value={cost.labourCost} onChange={e=>setCost({...cost,labourCost:e.target.value})}/></div><div><label>Packing Cost</label><input type="number" value={cost.packingCost} onChange={e=>setCost({...cost,packingCost:e.target.value})}/></div><div><label>Other Cost</label><input type="number" value={cost.otherCost} onChange={e=>setCost({...cost,otherCost:e.target.value})}/></div></div><div className="io-scroll"><table className="io-table"><thead><tr><th>Material</th><th>Qty</th><th>Rate</th></tr></thead><tbody>{cost.materials.map((x,i)=><tr key={i}><td><input value={x.name} onChange={e=>setCost(c=>({...c,materials:c.materials.map((v,j)=>j===i?{...v,name:e.target.value}:v)}))}/></td><td><input type="number" value={x.qty} onChange={e=>setCost(c=>({...c,materials:c.materials.map((v,j)=>j===i?{...v,qty:e.target.value}:v)}))}/></td><td><input type="number" value={x.rate} onChange={e=>setCost(c=>({...c,materials:c.materials.map((v,j)=>j===i?{...v,rate:e.target.value}:v)}))}/></td></tr>)}</tbody></table></div><button className="io-btn secondary" onClick={addCost}>+ Material</button> <button className="io-btn primary" onClick={async()=>{try{setCostResult(await post("/api/inventory/workflow/costing",cost))}catch(e){setErr(e.message)}}}>Calculate</button>{costResult&&<div className="io-card" style={{marginTop:12}}><b>Material ₹ {money(costResult.materialCost)} + Labour ₹ {money(costResult.labourCost)} + Packing ₹ {money(costResult.packingCost)} + Other ₹ {money(costResult.otherCost)} = Total ₹ {money(costResult.totalCost)}; Cost / Unit ₹ {money(costResult.costPerUnit)}</b></div>}</div>}
 {tab==="pi"&&<div className="io-card"><h3>Proforma Invoice</h3><div className="io-grid"><div><label>Customer / Party</label><Select value={pi.partyId} onChange={e=>setPi({...pi,partyId:e.target.value})}><option value="">Select customer</option>{m.customers.map(x=><option value={x._id} key={x._id}>{x.name}</option>)}</Select></div><div><label>Location</label><Select value={pi.location} onChange={e=>setPi({...pi,location:e.target.value})}><option value="">Select location</option>{m.locations.map(x=><option value={x.name} key={x._id}>{x.name}</option>)}</Select></div><div><label>Date</label><input type="date" value={pi.date} onChange={e=>setPi({...pi,date:e.target.value})}/></div><div><label>Reference</label><input value={pi.referenceNo} onChange={e=>setPi({...pi,referenceNo:e.target.value})}/></div></div><LineTable field="lines" lines={pi.lines} setForm={setPi} products={outputProducts}/><button className="io-btn secondary" onClick={addPiLine}>+ Product</button> <button className="io-btn primary" disabled={busy} onClick={()=>save("/api/inventory/workflow/pi",pi,()=>setPi({...pi,lines:[]}))}>Save PI</button></div>}
 {tab==="return"&&<div className="io-card"><h3>Returns / Quality / Expired</h3><div className="io-grid"><div><label>Return Type</label><Select value={ret.docType} onChange={e=>setRet({...ret,docType:e.target.value})}><option value="SALE_RETURN">Sale Return</option><option value="PURCHASE_RETURN">Purchase Return</option><option value="QUALITY_RETURN">Quality / Bad Goods</option><option value="EXPIRED_RETURN">Expired Goods</option></Select></div><div><label>Party</label><Select value={ret.partyId} onChange={e=>setRet({...ret,partyId:e.target.value})}><option value="">Select party</option>{[...(m.customers||[]),...(m.suppliers||[])].map(x=><option value={x._id} key={x._id}>{x.name}</option>)}</Select></div><div><label>Location</label><Select value={ret.location} onChange={e=>setRet({...ret,location:e.target.value})}><option value="">Select location</option>{m.locations.map(x=><option value={x.name} key={x._id}>{x.name}</option>)}</Select></div><div><label>Reference</label><input value={ret.referenceNo} onChange={e=>setRet({...ret,referenceNo:e.target.value})}/></div></div><LineTable field="lines" lines={ret.lines} setForm={setRet} products={inputProducts}/><button className="io-btn secondary" onClick={addRetLine}>+ Return Line</button> <button className="io-btn primary" disabled={busy} onClick={()=>save("/api/inventory/workflow/returns",ret,()=>setRet({...ret,lines:[]}))}>Post Return</button></div>}
 {tab==="damage"&&<div className="io-card"><h3>Damage Voucher</h3><div className="io-grid"><div><label>Date</label><input type="date" value={damage.date} onChange={e=>setDamage({...damage,date:e.target.value})}/></div><div><label>Location</label><Select value={damage.location} onChange={e=>setDamage({...damage,location:e.target.value})}><option value="">Select location</option>{m.locations.map(x=><option value={x.name} key={x._id}>{x.name}</option>)}</Select></div></div><LineTable field="lines" lines={damage.lines} setForm={setDamage} products={inputProducts}/><button className="io-btn secondary" onClick={()=>setDamage({...damage,lines:[...damage.lines,{itemName:"",itemType:"REJECTED",unit:"KG",qty:1,rate:0}]})}>+ Damage Line</button> <button className="io-btn primary" disabled={busy} onClick={()=>save("/api/inventory/workflow/damage",damage,()=>setDamage({...damage,date:today(),location:"",lines:[],notes:""}))}>Post Damage</button></div>}
{tab==="repack"&&<div className="io-card"><h3>Return Goods Open → Repacking</h3><div className="io-grid"><div><label>Location</label><Select value={repack.location} onChange={e=>setRepack({...repack,location:e.target.value})}><option value="">Select location</option>{m.locations.map(x=><option value={x.name} key={x._id}>{x.name}</option>)}</Select></div></div><h4>Source / Open Pack</h4><LineTable field="sourceLines" lines={repack.sourceLines} setForm={setRepack} products={inputProducts}/><button className="io-btn secondary" onClick={addSource}>+ Source</button><h4>Repacked Output</h4><LineTable field="outputLines" lines={repack.outputLines} setForm={setRepack} products={outputProducts}/><button className="io-btn secondary" onClick={addOutput}>+ Output</button> <button className="io-btn primary" disabled={busy} onClick={()=>save("/api/inventory/workflow/repack",repack,()=>setRepack({...repack,sourceLines:[],outputLines:[]}))}>Post Repacking</button></div>}
 {tab==="packing-conversion"&&<div className="io-card"><h3>Packing Conversion + Conversion Charge</h3><div className="io-grid"><div><label>Date</label><input type="date" value={pc.date} onChange={e=>setPc({...pc,date:e.target.value})}/></div><div><label>Location</label><Select value={pc.location} onChange={e=>setPc({...pc,location:e.target.value})}><option value="">Select location</option>{m.locations.map(x=><option value={x.name} key={x._id}>{x.name}</option>)}</Select></div><div><label>Conversion Charge</label><input type="number" min="0" step="0.01" value={pc.conversionCharge} onChange={e=>setPc({...pc,conversionCharge:e.target.value})}/></div></div><h4>Source / Raw or Loose Stock</h4><LineTable field="sourceLines" lines={pc.sourceLines} setForm={setPc} products={inputProducts}/><button className="io-btn secondary" onClick={()=>setPc({...pc,sourceLines:[...pc.sourceLines,{itemName:"",itemType:"RAW_MATERIAL",unit:"KG",qty:1,rate:0}]})}>+ Source</button><h4>Packed Output</h4><LineTable field="outputLines" lines={pc.outputLines} setForm={setPc} products={outputProducts}/><button className="io-btn secondary" onClick={()=>setPc({...pc,outputLines:[...pc.outputLines,{itemName:"",itemType:"PACKED_GOODS",unit:"PCS",qty:1,rate:0}]})}>+ Output</button> <button className="io-btn primary" disabled={busy} onClick={()=>save("/api/inventory/workflow/packing-conversion",pc,()=>setPc({...pc,date:today(),location:"",sourceLines:[],outputLines:[],conversionCharge:"",notes:""}))}>Post Packing Conversion</button></div>}
{tab==="stock"&&<div className="io-card"><h3>Stock Movement Ledger</h3><div className="io-scroll"><table className="io-table"><thead><tr><th>Date</th><th>Location</th><th>Item</th><th>Type</th><th>In</th><th>Out</th><th>Balance</th><th>Source</th></tr></thead><tbody>{ledger.map(x=><tr key={x._id}><td>{new Date(x.date).toLocaleString("en-IN")}</td><td>{x.location}</td><td>{x.itemName}</td><td>{x.itemType}</td><td>{x.qtyIn}</td><td>{x.qtyOut}</td><td>{x.balanceQty}</td><td>{x.sourceType} {x.sourceNo}</td></tr>)}</tbody></table></div></div>}
 {tab==="docs"&&<div className="io-card"><h3>Workflow Documents</h3><div className="io-scroll"><table className="io-table"><thead><tr><th>No</th><th>Type</th><th>Date</th><th>Party</th><th>Location</th><th>Value</th><th>Reference</th></tr></thead><tbody>{docs.map(x=><tr key={x._id}><td>{x.docNo}</td><td>{x.docType}</td><td>{new Date(x.date).toLocaleDateString("en-IN")}</td><td>{x.partyName||"-"}</td><td>{x.location||"-"}</td><td>₹ {money(x.totalValue)}</td><td>{x.referenceNo||"-"}</td></tr>)}</tbody></table></div></div>}
 </div>
}
function LineTable({field,lines,setForm,products}){return <div className="io-scroll"><table className="io-table"><thead><tr><th>Product</th><th>Type</th><th>Qty</th><th>Rate</th><th>Batch</th><th></th></tr></thead><tbody>{lines.map((x,i)=><tr key={i}><td><select value={x.itemId||""} onChange={e=>{const p=products.find(v=>v._id===e.target.value);setForm(s=>({...s,[field]:s[field].map((v,j)=>j===i?{...v,itemId:e.target.value,itemName:p?.name||"",itemType:p?.itemType||v.itemType,unit:p?.unit||v.unit}:v)}))}}><option value="">Select product</option>{products.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select></td><td>{x.itemType}</td><td><input type="number" value={x.qty} onChange={e=>setForm(s=>({...s,[field]:s[field].map((v,j)=>j===i?{...v,qty:e.target.value}:v)}))}/></td><td><input type="number" value={x.rate} onChange={e=>setForm(s=>({...s,[field]:s[field].map((v,j)=>j===i?{...v,rate:e.target.value}:v)}))}/></td><td><input value={x.batchNo||""} onChange={e=>setForm(s=>({...s,[field]:s[field].map((v,j)=>j===i?{...v,batchNo:e.target.value}:v)}))}/></td><td><button className="io-btn danger" onClick={()=>setForm(s=>({...s,[field]:s[field].filter((_,j)=>j!==i)}))}>×</button></td></tr>)}</tbody></table></div>}
