import React,{useEffect,useState} from "react";
const API_URL=(import.meta.env.VITE_API_URL||"https://office-management-system-ikx8.onrender.com").replace(/\/+$/,'');
const headers=()=>({"Content-Type":"application/json",Authorization:`Bearer ${localStorage.getItem('token')||localStorage.getItem('accessToken')||''}`});

export default function InventoryMasters(){
 const [data,setData]=useState({locations:[],suppliers:[],items:[]});
 const [open,setOpen]=useState(null),[mode,setMode]=useState('list'),[editing,setEditing]=useState(null),[search,setSearch]=useState('');
 const [msg,setMsg]=useState(''),[err,setErr]=useState(''),[saving,setSaving]=useState(false),[lookup,setLookup]=useState('');
 const blank={location:{name:'',code:'',pin:'',state:'',district:'',address:''},supplier:{name:'',gstin:'',gstStatus:'',state:'',district:'',pin:'',phone:'',address:''},product:{name:'',itemType:'RAW_MATERIAL',hsn:'',unit:'KG',defaultGstRate:'',defaultBarcode:''}};
 const [form,setForm]=useState(blank.location);
 async function load(){try{const r=await fetch(`${API_URL}/api/inventory/raw-material-masters`,{headers:headers()});const d=await r.json();if(!r.ok)throw Error(d.message||'Master load failed');setData({locations:d.locations||[],suppliers:d.suppliers||[],items:d.items||[]});}catch(e){setErr(e.message)}}
 useEffect(()=>{load()},[]);
 function start(type){setOpen(type);setMode('list');setEditing(null);setSearch('');setForm({...blank[type]});setMsg('');setErr('');setLookup('')}
 function edit(type,row){setMode('form');setEditing(row);setLookup('');setForm(type==='location'?{name:row.name||'',code:row.code||'',pin:row.pin||'',state:row.state||'',district:row.district||'',address:row.address||''}:type==='supplier'?{name:row.name||'',gstin:row.gstin||'',gstStatus:row.gstStatus||'',state:row.state||'',district:row.district||'',pin:row.pin||'',phone:row.phone||'',address:row.address||''}:{name:row.name||'',itemType:row.itemType||'RAW_MATERIAL',hsn:row.hsn||'',unit:row.unit||'KG',defaultGstRate:row.defaultGstRate??'',defaultBarcode:row.defaultBarcode||''});setErr('');setMsg('')}
 async function lookupPin(){const pin=String(form.pin||'').replace(/\D/g,'');if(pin.length!==6)return;setLookup('PIN searching...');try{const r=await fetch(`${API_URL}/api/inventory/masters/pincode/${pin}`,{headers:headers()});const d=await r.json();if(!r.ok)throw Error(d.message||'PIN not found');setForm(f=>({...f,pin,district:d.district||'',state:d.state||'',address:f.address||d.address||''}));setLookup(`✓ ${d.postOffices?.slice(0,3).join(', ')||'PIN found'}`)}catch(e){setLookup(`⚠ ${e.message}`)}}
 async function lookupGST(){const gst=String(form.gstin||'').trim().toUpperCase();if(gst.length!==15)return;setLookup('GSTIN verifying...');try{const r=await fetch(`${API_URL}/api/inventory/masters/gstin/${gst}`,{headers:headers()});const d=await r.json();if(!r.ok)throw Error(d.message||'GSTIN verification failed');setForm(f=>({...f,gstin:gst,name:d.name||f.name,state:d.state||f.state,district:d.district||f.district,pin:d.pincode||f.pin,address:d.address||f.address,gstStatus:d.status||f.gstStatus}));setLookup(d.verified?`✓ GST ${d.status||'verified'} — details filled automatically`:`✓ GST format OK — state filled automatically`)}catch(e){setLookup(`⚠ ${e.message}`)}}
 async function save(){setSaving(true);setErr('');setMsg('');try{const base=open==='location'?'locations':open==='supplier'?'suppliers':'items';const url=`${API_URL}/api/inventory/masters/${base}${editing?`/${editing._id}`:''}`;const r=await fetch(url,{method:editing?'PUT':'POST',headers:headers(),body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw Error(d.message||'Save failed');setMsg(d.message||'Saved');setEditing(null);setMode('list');setForm({...blank[open]});await load()}catch(e){setErr(e.message)}finally{setSaving(false)}}
 async function del(type,row){if(!window.confirm(`Delete ${row.name}?`))return;try{const base=type==='location'?'locations':type==='supplier'?'suppliers':'items';const r=await fetch(`${API_URL}/api/inventory/masters/${base}/${row._id}`,{method:'DELETE',headers:headers()});const d=await r.json();if(!r.ok)throw Error(d.message||'Delete failed');setMsg(d.message||'Deleted');await load()}catch(e){setErr(e.message)}}
 const list=open==='location'?data.locations:open==='supplier'?data.suppliers:data.items;const filtered=list.filter(x=>(`${x.name||''} ${x.code||''} ${x.gstin||''} ${x.pin||''}`).toLowerCase().includes(search.toLowerCase()));
 return <div className="im-page"><div className="im-head"><div><div className="kicker">INVENTORY</div><h1>Inventory Masters</h1><p>Location, Product and Supplier master management</p></div></div>
 <div className="round-grid"><button onClick={()=>start('location')}><span>📍</span><b>Location</b><small>{data.locations.length} records</small></button><button onClick={()=>start('product')}><span>📦</span><b>Product</b><small>{data.items.length} records</small></button><button onClick={()=>start('supplier')}><span>🏢</span><b>Supplier</b><small>{data.suppliers.length} records</small></button></div>
 {msg&&<div className="ok">✓ {msg}</div>}{err&&<div className="bad">⚠ {err}</div>}
 {open&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(null)}><div className="modal"><div className="modal-head"><div><div className="kicker">MASTER</div><h2>{open==='location'?'Location / Godown':open==='supplier'?'Supplier':'Product / Item'}</h2></div><button className="x" onClick={()=>setOpen(null)}>×</button></div>
 <div className="tabs"><button className={mode==='list'?'active':''} onClick={()=>{setMode('list');setEditing(null)}}>List</button><button className={mode==='form'?'active':''} onClick={()=>{setMode('form');setEditing(null);setForm({...blank[open]});setLookup('')}}>+ Create</button></div>
 {mode==='list'?<><div className="search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${open} name / code / GSTIN / PIN...`}/></div><div className="list">{filtered.length===0?<div className="empty">No matching record found.</div>:filtered.map(row=><div className="row" key={row._id}><div><b>{row.name}</b><small>{open==='location'?`${row.code||'Auto code'} · ${row.pin||''} · ${row.district||''} · ${row.state||''}`:open==='supplier'?`${row.gstin||'No GSTIN'} · ${row.gstStatus||''} · ${row.pin||''} · ${row.state||''}`:`${row.itemType||''} · ${row.unit||''}`}</small></div><div className="actions"><button onClick={()=>edit(open,row)}>✏ Edit</button><button className="danger" onClick={()=>del(open,row)}>🗑 Delete</button></div></div>)}</div></>:<div className="form">
 {open==='location'&&<><label>Name *</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><label>Location Code <em>Automatic</em></label><input value={form.code||'Will be generated automatically (LOC-YYYY-00001)'} readOnly className="readonly"/><label>PIN Code *</label><input inputMode="numeric" maxLength="6" value={form.pin} onChange={e=>setForm({...form,pin:e.target.value.replace(/\D/g,'').slice(0,6)})} onBlur={lookupPin}/><label>State</label><input value={form.state} readOnly className="readonly"/><label>District</label><input value={form.district} readOnly className="readonly"/><label>Address</label><textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></>}
 {open==='supplier'&&<><label>Supplier Name *</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><label>GSTIN</label><input maxLength="15" value={form.gstin} onChange={e=>setForm({...form,gstin:e.target.value.toUpperCase().replace(/\s/g,'').slice(0,15)})} onBlur={lookupGST}/><label>GST Status</label><input value={form.gstStatus} readOnly className="readonly"/><label>State</label><input value={form.state} readOnly className="readonly"/><label>District</label><input value={form.district} readOnly className="readonly"/><label>PIN Code</label><input value={form.pin} readOnly className="readonly"/><label>Phone</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><label>Address</label><textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></>}
 {open==='product'&&<><label>Name *</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><label>Item Type</label><select value={form.itemType} onChange={e=>setForm({...form,itemType:e.target.value})}><option value="RAW_MATERIAL">Raw Material</option><option value="GRADE">Grade</option><option value="FINISHED_GOODS">Finished Goods</option></select><label>HSN</label><input value={form.hsn} onChange={e=>setForm({...form,hsn:e.target.value})}/><label>Unit</label><input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/><label>Default GST %</label><input type="number" value={form.defaultGstRate} onChange={e=>setForm({...form,defaultGstRate:e.target.value})}/><label>Barcode</label><input value={form.defaultBarcode} onChange={e=>setForm({...form,defaultBarcode:e.target.value})}/></>}
 {lookup&&<div className="lookup">{lookup}</div>}<div className="form-actions"><button onClick={()=>{setMode('list');setEditing(null)}}>Cancel</button><button className="primary" disabled={saving} onClick={save}>{saving?'Saving...':editing?'Update':'Create'}</button></div></div>}
 </div></div>}
 <style>{`.im-page{padding:28px;background:#f5f7fb;min-height:100vh;color:#172b4d}.im-head h1{margin:4px 0;font-size:26px}.im-head p{color:#667085;font-size:12px}.kicker{font-size:10px;font-weight:800;letter-spacing:1px;color:#98a2b3}.round-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:25px}.round-grid button{height:150px;border:1px solid #e4e7ec;background:#fff;border-radius:22px;box-shadow:0 5px 18px #1018280d;display:flex;flex-direction:column;align-items:center;justify-content:center;cursor:pointer;transition:.15s}.round-grid button:hover{transform:translateY(-2px)}.round-grid span{font-size:36px}.round-grid b{font-size:17px;margin-top:8px}.round-grid small{color:#667085;margin-top:5px}.ok,.bad{margin-top:16px;padding:11px;border-radius:9px}.ok{background:#ecfdf3;color:#027a48}.bad{background:#fef3f2;color:#b42318}.modal-backdrop{position:fixed;inset:0;background:#10182899;display:flex;align-items:center;justify-content:center;z-index:1000;padding:20px}.modal{background:#fff;width:min(720px,100%);max-height:90vh;overflow:auto;border-radius:16px;padding:22px}.modal-head{display:flex;justify-content:space-between}.modal-head h2{margin:4px 0 15px}.x{border:0;background:#f2f4f7;border-radius:50%;width:34px;height:34px;font-size:22px;cursor:pointer}.tabs{display:flex;gap:8px;border-bottom:1px solid #eaecf0;margin-bottom:15px}.tabs button{border:0;background:transparent;padding:10px 15px;cursor:pointer;font-weight:700}.tabs .active{color:#245a96;border-bottom:2px solid #245a96}.search input,.form input,.form select,.form textarea{width:100%;box-sizing:border-box;padding:11px;border:1px solid #d0d5dd;border-radius:8px;margin-bottom:12px}.form em{float:right;color:#027a48;font-style:normal}.readonly{background:#f2f4f7}.lookup{margin:-4px 0 12px;padding:9px;border-radius:8px;background:#f0f9ff;color:#075985;font-size:12px}.list{margin-top:12px}.row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px;border-bottom:1px solid #eaecf0}.row small{display:block;color:#667085;margin-top:4px}.actions{display:flex;gap:7px}.actions button,.form-actions button{border:1px solid #d0d5dd;background:#fff;border-radius:7px;padding:8px 11px;cursor:pointer}.actions .danger{color:#b42318}.form label{display:block;font-size:11px;font-weight:700;margin:6px 0}.form textarea{min-height:70px}.form-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:8px}.form-actions .primary{background:#245a96;color:#fff;border-color:#245a96}.empty{text-align:center;padding:30px;color:#98a2b3}@media(max-width:700px){.round-grid{grid-template-columns:1fr}.row{align-items:flex-start;flex-direction:column}.actions{width:100%}}`}</style></div>
}
