import React,{useEffect,useState} from 'react';
const API=import.meta.env.VITE_API_URL||'https://office-management-system-ikx8.onrender.com';
const H=()=>({'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('token')||''}`});
export default function Inventory(){const [tab,setTab]=useState('items'),[items,setItems]=useState([]),[jobs,setJobs]=useState([]),[msg,setMsg]=useState(''),[err,setErr]=useState('');const [item,setItem]=useState({name:'',code:'',stockGroup:'',unit:'KG',openingQty:'',openingRate:''});const [job,setJob]=useState({customerName:'',product:'',inputQty:'',unit:'KG',location:'',notes:''});const [process,setProcess]=useState({jobId:'',type:'Grading',inputQty:'',outputQty:'',wastageQty:'',grade:'',packingSize:'',remarks:''});
async function load(){try{const [a,b]=await Promise.all([fetch(API+'/api/inventory/stock-items',{headers:H()}),fetch(API+'/api/inventory/job-orders',{headers:H()})]);const ad=await a.json(),bd=await b.json();if(!a.ok)throw Error(ad.message);setItems(ad.items||[]);setJobs(bd.jobs||[])}catch(e){setErr(e.message)}}useEffect(()=>{load()},[]);
async function post(url,body){const r=await fetch(API+url,{method:'POST',headers:H(),body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.message||'Save failed');return d}
async function saveItem(e){e.preventDefault();try{await post('/api/inventory/stock-items',item);setItem({name:'',code:'',stockGroup:'',unit:'KG',openingQty:'',openingRate:''});setMsg('Stock item saved');load()}catch(e){setErr(e.message)}}
async function saveJob(e){e.preventDefault();try{await post('/api/inventory/job-orders',job);setJob({customerName:'',product:'',inputQty:'',unit:'KG',location:'',notes:''});setMsg('Job Order created');load()}catch(e){setErr(e.message)}}
async function saveProcess(e){e.preventDefault();try{await post(`/api/inventory/job-orders/${process.jobId}/processes`,process);setMsg(process.type+' saved');load()}catch(e){setErr(e.message)}}
return <div style={{padding:24,background:'#f5f7fb',minHeight:'100vh',fontFamily:'Arial'}}><h1>Inventory</h1><p>Stock, Job Order, Grading and Packing</p><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:16}}>{[['items','Stock Items'],['jobs','Job Orders'],['grading','Grading'],['packing','Packing']].map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</div>{msg&&<div style={ok}>{msg}</div>}{err&&<div style={er}>{err}</div>}
{tab==='items'&&<div style={grid}><form style={card} onSubmit={saveItem}><h2>Stock Item</h2><input placeholder="Item name" value={item.name} onChange={e=>setItem({...item,name:e.target.value})}/><input placeholder="Item code" value={item.code} onChange={e=>setItem({...item,code:e.target.value})}/><input placeholder="Stock Group" value={item.stockGroup} onChange={e=>setItem({...item,stockGroup:e.target.value})}/><input placeholder="Unit" value={item.unit} onChange={e=>setItem({...item,unit:e.target.value})}/><input type="number" placeholder="Opening Qty" value={item.openingQty} onChange={e=>setItem({...item,openingQty:e.target.value})}/><input type="number" placeholder="Opening Rate" value={item.openingRate} onChange={e=>setItem({...item,openingRate:e.target.value})}/><button>Save Item</button></form><div style={card}><h2>Stock Items</h2><table><thead><tr><th>Name</th><th>Code</th><th>Unit</th><th>Qty</th></tr></thead><tbody>{items.map(i=><tr key={i._id}><td>{i.name}</td><td>{i.code}</td><td>{i.unit}</td><td>{i.currentQty}</td></tr>)}</tbody></table></div></div>}
{tab==='jobs'&&<div style={grid}><form style={card} onSubmit={saveJob}><h2>New Job Order</h2><input placeholder="Customer / Party" value={job.customerName} onChange={e=>setJob({...job,customerName:e.target.value})}/><input placeholder="Product" value={job.product} onChange={e=>setJob({...job,product:e.target.value})}/><input type="number" placeholder="Input Qty" value={job.inputQty} onChange={e=>setJob({...job,inputQty:e.target.value})}/><input placeholder="Unit" value={job.unit} onChange={e=>setJob({...job,unit:e.target.value})}/><input placeholder="Location" value={job.location} onChange={e=>setJob({...job,location:e.target.value})}/><textarea placeholder="Notes" value={job.notes} onChange={e=>setJob({...job,notes:e.target.value})}/><button>Create Job Order</button></form><div style={card}><h2>Job Orders</h2><table><thead><tr><th>No.</th><th>Customer</th><th>Product</th><th>Qty</th><th>Status</th><th>Process</th></tr></thead><tbody>{jobs.map(j=><tr key={j._id}><td>{j.jobNo}</td><td>{j.customerName}</td><td>{j.product}</td><td>{j.inputQty} {j.unit}</td><td>{j.status}</td><td>{j.processes?.length||0}</td></tr>)}</tbody></table></div></div>}
{(tab==='grading'||tab==='packing')&&<form style={card} onSubmit={saveProcess}><h2>{tab==='grading'?'Grading Entry':'Packing Entry'}</h2><select value={process.jobId} onChange={e=>setProcess({...process,jobId:e.target.value,type:tab==='grading'?'Grading':'Packing'})}><option value="">Select Job Order</option>{jobs.map(j=><option key={j._id} value={j._id}>{j.jobNo} - {j.product}</option>)}</select><input type="number" placeholder="Input Qty" value={process.inputQty} onChange={e=>setProcess({...process,inputQty:e.target.value})}/><input type="number" placeholder="Output Qty" value={process.outputQty} onChange={e=>setProcess({...process,outputQty:e.target.value})}/><input type="number" placeholder="Wastage / Rejection Qty" value={process.wastageQty} onChange={e=>setProcess({...process,wastageQty:e.target.value})}/>{tab==='grading'?<input placeholder="Grade (A/B/etc.)" value={process.grade} onChange={e=>setProcess({...process,grade:e.target.value})}/>:<input placeholder="Packing Size (10 KG Bag etc.)" value={process.packingSize} onChange={e=>setProcess({...process,packingSize:e.target.value})}/>}<textarea placeholder="Remarks" value={process.remarks} onChange={e=>setProcess({...process,remarks:e.target.value})}/><button>Save {tab==='grading'?'Grading':'Packing'}</button></form>}
</div>}
const card={background:'#fff',padding:20,borderRadius:14,boxShadow:'0 4px 18px rgba(0,0,0,.06)'};const grid={display:'grid',gridTemplateColumns:'minmax(280px,380px) 1fr',gap:18};const ok={padding:12,background:'#e9f8ef',borderRadius:8,marginBottom:12};const er={padding:12,background:'#fff0f0',borderRadius:8,marginBottom:12};
