import React,{useEffect,useState} from "react";
import {hrApi} from "../lib/hrApi.js";

export default function LeaveManagement(){
 const [employees,setEmployees]=useState([]),[rows,setRows]=useState([]),[form,setForm]=useState({employeeId:"",leaveType:"Casual",fromDate:"",toDate:"",reason:""}),[error,setError]=useState("");
 async function load(){try{const[e,l]=await Promise.all([hrApi.employees(),hrApi.leaves()]);setEmployees(e.employees||[]);setRows(l.leaves||[]);if(!form.employeeId&&e.employees?.[0])setForm(f=>({...f,employeeId:e.employees[0]._id}))}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();try{await hrApi.createLeave(form);load()}catch(e){setError(e.message)}}
 async function status(id,value){try{await hrApi.updateLeaveStatus(id,value);load()}catch(e){setError(e.message)}}
 return <main style={S.page}><h1>Leave Management</h1><p style={S.sub}>Apply, approve and track employee leave</p>{error&&<p style={S.error}>{error}</p>}
 <form onSubmit={save} style={S.card}><select style={S.input} value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}>{employees.map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select><select style={S.input} value={form.leaveType} onChange={e=>setForm({...form,leaveType:e.target.value})}>{["Casual","Sick","Earned","Unpaid","Other"].map(x=><option key={x}>{x}</option>)}</select><input type="date" style={S.input} value={form.fromDate} onChange={e=>setForm({...form,fromDate:e.target.value})}/><input type="date" style={S.input} value={form.toDate} onChange={e=>setForm({...form,toDate:e.target.value})}/><input placeholder="Reason" style={S.input} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/><button style={S.btn}>Apply Leave</button></form>
 <section style={S.card}>{rows.map(x=><div style={S.row} key={x._id}><b>{x.employeeId?.name}</b><span>{x.leaveType}</span><span>{new Date(x.fromDate).toLocaleDateString("en-IN")} - {new Date(x.toDate).toLocaleDateString("en-IN")}</span><span style={S.badge}>{x.status}</span>{x.status==="Pending"?<span><button onClick={()=>status(x._id,"Approved")} style={S.ok}>Approve</button> <button onClick={()=>status(x._id,"Rejected")} style={S.no}>Reject</button></span>:<span/>}</div>)}</section></main>
}
const S={page:{padding:24,background:"#f5f7fb",minHeight:"100vh",fontFamily:"Arial"},sub:{color:"#667085"},card:{background:"#fff",padding:20,borderRadius:18,marginTop:18,boxShadow:"0 8px 24px rgba(15,23,42,.06)"},input:{padding:12,border:"1px solid #d9e1ec",borderRadius:10,margin:5},btn:{padding:"12px 18px",background:"#1d4f91",color:"#fff",border:0,borderRadius:10,fontWeight:700},row:{display:"grid",gridTemplateColumns:"1.1fr .8fr 1.4fr .8fr 1.2fr",gap:10,padding:"13px 0",borderBottom:"1px solid #eee",alignItems:"center"},badge:{padding:"5px 9px",borderRadius:20,background:"#fff5d6",color:"#946200",fontSize:12},ok:{border:0,borderRadius:8,padding:"7px 10px",background:"#eaf7ef",color:"#16834b"},no:{border:0,borderRadius:8,padding:"7px 10px",background:"#fee4e2",color:"#b42318"},error:{background:"#fee4e2",color:"#b42318",padding:10,borderRadius:10}};
