import React,{useEffect,useMemo,useState} from "react";
const API=(import.meta.env.VITE_API_URL||"https://office-management-system-ikx8.onrender.com").replace(/\/+$/,'');
const auth=()=>({"Content-Type":"application/json",Authorization:`Bearer ${localStorage.getItem("token")||""}`});
async function api(path,opt={}){const r=await fetch(`${API}/api/inventory${path}`,{...opt,headers:{...auth(),...(opt.headers||{})}});const d=await r.json();if(!r.ok)throw new Error(d.message||"Request failed");return d}
const today=()=>new Date().toISOString().slice(0,10); const money=n=>Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
function Input({label,...p}){return <label className="mf"><span>{label}</span><input {...p}/></label>}
function Select({label,children,...p}){return <label className="mf"><span>{label}</span><select {...p}>{children}</select></label>}
function Lines({items,setItems,type}){return <div className="scroll"><table><thead><tr><th>Item</th><th>Unit</th><th>Qty</th><th>Rate</th><th>Batch</th><th>Barcode</th><th></th></tr></thead><tbody>{items.map((x,i)=><tr key={i}><td><input value={x.itemName} onChange={e=>setItems(a=>a.map((v,j)=>j===i?{...v,itemName:e.target.value}:v))}/></td><td><input value={x.unit||"KG"} onChange={e=>setItems(a=>a.map((v,j)=>j===i?{...v,unit:e.target.value}:v))}/></td><td><input type="number" min="0" value={x.qty} onChange={e=>setItems(a=>a.map((v,j)=>j===i?{...v,qty:e.target.value}:v))}/></td><td><input type="number" min="0" value={x.rate} onChange={e=>setItems(a=>a.map((v,j)=>j===i?{...v,rate:e.target.value}:v))}/></td><td><input value={x.batchNo||""} onChange={e=>setItems(a=>a.map((v,j)=>j===i?{...v,batchNo:e.target.value}:v))}/></td><td><input value={x.barcode||""} onChange={e=>setItems(a=>a.map((v,j)=>j===i?{...v,barcode:e.target.value}:v))}/></td><td><button className="danger" onClick={()=>setItems(a=>a.filter((_,j)=>j!==i))}>×</button></td></tr>)}</tbody></table></div>}
function StockTable({items,title}){return <div className="card"><h3>{title}</h3><div className="scroll"><table><thead><tr><th>Item</th><th>Type</th><th>Location</th><th>Batch</th><th>Qty</th><th>Unit</th><th>Avg Rate</th><th>Value</th></tr></thead><tbody>{items.map(x=><tr key={x._id}><td>{x.itemName}</td><td>{x.itemType}</td><td>{x.location}</td><td>{x.batchNo||"-"}</td><td>{money(x.qty)}</td><td>{x.unit}</td><td>₹ {money(x.averageRate)}</td><td>₹ {money(x.stockValue)}</td></tr>)}</tbody></table></div></div>}
export default function Manufacturing(){const [tab,setTab]=useState("purchase"),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false),[stock,setStock]=useState([]),[jobs,setJobs]=useState([]),[sales,setSales]=useState([]),[gst,setGst]=useState(null);
const [purchase,setPurchase]=useState({date:today(),location:"",supplierName:"",supplierGSTIN:"",supplierInvoiceNo:"",supplierInvoiceDate:"",transportCost:"",otherCost:"",remarks:""});
const blank=()=>({itemName:"",unit:"KG",qty:"",rate:"",batchNo:"",barcode:""});const [pLines,setPLines]=useState([blank()]);
const [job,setJob]=useState({date:today(),location:"",labourCost:"",transportCost:"",otherCost:"",notes:""}),[sources,setSources]=useState([blank()]),[outputs,setOutputs]=useState([blank()]);
const [sale,setSale]=useState({date:today(),location:"",customerName:"",customerGSTIN:"",customerState:"",supplierState:"",placeOfSupply:"",remarks:""}),[sLines,setSLines]=useState([{...blank(),gstRate:"",gstType:"CGST_SGST"}]);
const [jobType,setJobType]=useState("GRADING");
async function refresh(){try{const [r,g,f,s,j]=await Promise.all([api('/stock?itemType=RAW_MATERIAL'),api('/stock?itemType=GRADE'),api('/stock?itemType=FINISHED_GOODS'),api('/sales'),api('/job-orders')]);setStock([...r.items,...g.items,...f.items]);setSales(s.items||[]);setJobs(j.items||[])}catch(e){setErr(e.message)}}
useEffect(()=>{refresh()},[]);useEffect(()=>{if(tab==="gst")api('/gst-report').then(setGst).catch(e=>setErr(e.message))},[tab]);
async function savePurchase(){setBusy(true);setErr("");try{const d=await api('/raw-material-purchases',{method:'POST',body:JSON.stringify({...purchase,lines:pLines})});setMsg(d.message);setPLines([blank()]);await refresh()}catch(e){setErr(e.message)}finally{setBusy(false)}}
async function saveJob(forceType=jobType){setBusy(true);setErr("");try{const d=await api('/job-orders',{method:'POST',body:JSON.stringify({...job,type:forceType,sourceItems:sources,outputItems:outputs})});setMsg(d.message);setSources([blank()]);setOutputs([blank()]);await refresh()}catch(e){setErr(e.message)}finally{setBusy(false)}}
async function saveSale(){setBusy(true);setErr("");try{const d=await api('/sales',{method:'POST',body:JSON.stringify({...sale,lines:sLines})});setMsg(d.message);setSLines([{...blank(),gstRate:"",gstType:"CGST_SGST"}]);await refresh()}catch(e){setErr(e.message)}finally{setBusy(false)}}
const tabs=[['purchase','Purchase'],['grading','Grading Job Order'],['grade','Grade Stock'],['fgjob','Finished Goods Job'],['fg','Finished Goods Stock'],['sales','Sales'],['gst','GST Reports']];
return <main className="manufacturing"><style>{`.manufacturing{padding:20px;max-width:1500px;margin:auto;font-family:Inter,Arial,sans-serif;color:#172b4d}.top{display:flex;justify-content:space-between;gap:15px;align-items:center;margin-bottom:15px}.top h1{margin:0}.tabs{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:15px}.tab{border:1px solid #d0d5dd;background:#fff;padding:10px 13px;border-radius:8px;cursor:pointer}.tab.on{background:#175cd3;color:#fff;border-color:#175cd3}.card{background:#fff;border:1px solid #e4e7ec;border-radius:12px;padding:16px;margin-bottom:15px;box-shadow:0 2px 10px #1018280d}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.mf{display:grid;gap:5px;font-size:12px;font-weight:600}.mf input,.mf select,.card input{padding:9px;border:1px solid #d0d5dd;border-radius:7px;box-sizing:border-box;width:100%}.wide{grid-column:span 2}.btn{border:0;border-radius:8px;padding:10px 14px;background:#175cd3;color:white;font-weight:700;cursor:pointer}.secondary{background:#eef2f6;color:#344054}.danger{border:0;background:#fee4e2;color:#b42318;padding:7px 10px;border-radius:6px}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;min-width:850px}th,td{border-bottom:1px solid #eaecf0;padding:9px;text-align:left;font-size:12px;white-space:nowrap}th{background:#f8fafc}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:12px}.msg{background:#ecfdf3;color:#027a48;padding:10px;border-radius:8px;margin-bottom:12px}.err{background:#fef3f2;color:#b42318;padding:10px;border-radius:8px;margin-bottom:12px}.muted{color:#667085;font-size:13px}.summary{display:flex;gap:25px;justify-content:flex-end;margin-top:12px}.job-head{display:flex;gap:10px;align-items:center;margin-bottom:10px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}}`}</style>
<div className="top"><div><h1>Purchase → Production → Sales → GST</h1><div className="muted">Raw Stock → Grade Stock → Finished Goods Stock with stock-controlled job orders.</div></div><button className="btn secondary" onClick={refresh}>Refresh</button></div>
<div className="tabs">{tabs.map(([k,n])=><button className={`tab ${tab===k?'on':''}`} onClick={()=>{setTab(k);setMsg('');setErr('')}} key={k}>{n}</button>)}</div>{msg&&<div className="msg">{msg}</div>}{err&&<div className="err">{err}</div>}
{tab==='purchase'&&<><div className="card"><h3>Raw Material Purchase</h3><div className="grid"><Input label="Date" type="date" value={purchase.date} onChange={e=>setPurchase({...purchase,date:e.target.value})}/><Input label="Location / Godown" value={purchase.location} onChange={e=>setPurchase({...purchase,location:e.target.value})}/><Input label="Supplier" value={purchase.supplierName} onChange={e=>setPurchase({...purchase,supplierName:e.target.value})}/><Input label="Supplier GSTIN" value={purchase.supplierGSTIN} onChange={e=>setPurchase({...purchase,supplierGSTIN:e.target.value.toUpperCase()})}/><Input label="Invoice No" value={purchase.supplierInvoiceNo} onChange={e=>setPurchase({...purchase,supplierInvoiceNo:e.target.value})}/><Input label="Invoice Date" type="date" value={purchase.supplierInvoiceDate} onChange={e=>setPurchase({...purchase,supplierInvoiceDate:e.target.value})}/><Input label="Transport Cost" type="number" value={purchase.transportCost} onChange={e=>setPurchase({...purchase,transportCost:e.target.value})}/><Input label="Other Cost" type="number" value={purchase.otherCost} onChange={e=>setPurchase({...purchase,otherCost:e.target.value})}/></div></div><div className="card"><h3>Raw Material Lines</h3><Lines items={pLines} setItems={setPLines}/><button className="btn secondary" onClick={()=>setPLines([...pLines,blank()])}>+ Add Raw Material</button><div className="actions"><button className="btn" disabled={busy} onClick={savePurchase}>{busy?'Posting...':'Post Purchase → Raw Stock'}</button></div></div></>}
{(tab==='grading'||tab==='fgjob')&&<div className="card"><div className="job-head"><h3 style={{margin:0}}>{tab==='grading'?'Grading Job Order':'Finished Goods Job Order'}</h3><Select label="" value={jobType} onChange={e=>setJobType(e.target.value)}><option value="GRADING">GRADING: Raw → Grades</option><option value="FINISHED_GOODS">FINISHED GOODS: Grade → FG</option></Select></div><div className="grid"><Input label="Date" type="date" value={job.date} onChange={e=>setJob({...job,date:e.target.value})}/><Input label="Location" value={job.location} onChange={e=>setJob({...job,location:e.target.value})}/><Input label="Labour Cost" type="number" value={job.labourCost} onChange={e=>setJob({...job,labourCost:e.target.value})}/><Input label="Transport Cost" type="number" value={job.transportCost} onChange={e=>setJob({...job,transportCost:e.target.value})}/><Input label="Other Production Cost" type="number" value={job.otherCost} onChange={e=>setJob({...job,otherCost:e.target.value})}/></div><h4>Source Stock (will decrease)</h4><Lines items={sources} setItems={setSources}/><button className="btn secondary" onClick={()=>setSources([...sources,blank()])}>+ Source</button><h4>Output Stock (will increase)</h4><Lines items={outputs} setItems={setOutputs}/><button className="btn secondary" onClick={()=>setOutputs([...outputs,blank()])}>+ Output</button><div className="actions"><button className="btn" disabled={busy} onClick={()=>{const t=tab==='grading'?'GRADING':'FINISHED_GOODS';setJobType(t);saveJob(t)}}>{busy?'Posting...':'Post Job Order & Update Stock'}</button></div></div>}
{tab==='grade'&&<StockTable items={stock.filter(x=>x.itemType==='GRADE')} title="Grade Stock"/>}{tab==='fg'&&<StockTable items={stock.filter(x=>x.itemType==='FINISHED_GOODS')} title="Finished Goods Stock"/>}
{tab==='sales'&&<><div className="card"><h3>Finished Goods Sale</h3><div className="grid"><Input label="Date" type="date" value={sale.date} onChange={e=>setSale({...sale,date:e.target.value})}/><Input label="Location" value={sale.location} onChange={e=>setSale({...sale,location:e.target.value})}/><Input label="Customer / Party" value={sale.customerName} onChange={e=>setSale({...sale,customerName:e.target.value})}/><Input label="Customer GSTIN" value={sale.customerGSTIN} onChange={e=>setSale({...sale,customerGSTIN:e.target.value.toUpperCase()})}/><Input label="Supplier State" value={sale.supplierState} onChange={e=>setSale({...sale,supplierState:e.target.value})}/><Input label="Place of Supply" value={sale.placeOfSupply} onChange={e=>setSale({...sale,placeOfSupply:e.target.value})}/><Input label="Customer State" value={sale.customerState} onChange={e=>setSale({...sale,customerState:e.target.value})}/></div></div><div className="card"><h3>Sale Lines</h3><div className="scroll"><table><thead><tr><th>FG Item</th><th>Unit</th><th>Qty</th><th>Rate</th><th>Batch</th><th>Barcode</th><th>HSN</th><th>GST %</th><th>Tax Type</th><th></th></tr></thead><tbody>{sLines.map((x,i)=><tr key={i}>{['itemName','unit','qty','rate','batchNo','barcode','hsn','gstRate'].map(k=><td key={k}><input type={['qty','rate','gstRate'].includes(k)?'number':'text'} value={x[k]||''} onChange={e=>setSLines(a=>a.map((v,j)=>j===i?{...v,[k]:e.target.value}:v))}/></td>)}<td><select value={x.gstType} onChange={e=>setSLines(a=>a.map((v,j)=>j===i?{...v,gstType:e.target.value}:v))}><option value="NONE">None</option><option value="CGST_SGST">CGST+SGST</option><option value="IGST">IGST</option></select></td><td><button className="danger" onClick={()=>setSLines(a=>a.filter((_,j)=>j!==i))}>×</button></td></tr>)}</tbody></table></div><button className="btn secondary" onClick={()=>setSLines([...sLines,{...blank(),gstRate:'',gstType:'CGST_SGST'}])}>+ Sale Line</button><div className="actions"><button className="btn" disabled={busy} onClick={saveSale}>{busy?'Posting...':'Post Sale & Reduce FG Stock'}</button></div></div><div className="card"><h3>Sales List</h3><div className="scroll"><table><thead><tr><th>Invoice</th><th>Date</th><th>Customer</th><th>Location</th><th>Taxable</th><th>CGST</th><th>SGST</th><th>IGST</th><th>Total</th></tr></thead><tbody>{sales.map(x=><tr key={x._id}><td>{x.invoiceNo}</td><td>{new Date(x.date).toLocaleDateString('en-IN')}</td><td>{x.customerName}</td><td>{x.location}</td><td>₹ {money(x.subtotal)}</td><td>₹ {money(x.totalCGST)}</td><td>₹ {money(x.totalSGST)}</td><td>₹ {money(x.totalIGST)}</td><td>₹ {money(x.grandTotal)}</td></tr>)}</tbody></table></div></div></>}
{tab==='gst'&&<div className="card"><h3>GST Input / Output Summary</h3>{gst?<><div className="grid"><div><b>Input Taxable</b><h2>₹ {money(gst.summary.input.taxable)}</h2></div><div><b>Input CGST</b><h2>₹ {money(gst.summary.input.cgst)}</h2></div><div><b>Input SGST</b><h2>₹ {money(gst.summary.input.sgst)}</h2></div><div><b>Input IGST</b><h2>₹ {money(gst.summary.input.igst)}</h2></div><div><b>Output Taxable</b><h2>₹ {money(gst.summary.output.taxable)}</h2></div><div><b>Output CGST</b><h2>₹ {money(gst.summary.output.cgst)}</h2></div><div><b>Output SGST</b><h2>₹ {money(gst.summary.output.sgst)}</h2></div><div><b>Output IGST</b><h2>₹ {money(gst.summary.output.igst)}</h2></div></div><h4>GST Document Ledger</h4><div className="scroll"><table><thead><tr><th>Type</th><th>Document</th><th>Date</th><th>Party</th><th>GSTIN</th><th>HSN</th><th>Taxable</th><th>CGST</th><th>SGST</th><th>IGST</th></tr></thead><tbody>{gst.rows.map(x=><tr key={x._id}><td>{x.sourceType}</td><td>{x.documentNo}</td><td>{new Date(x.date).toLocaleDateString('en-IN')}</td><td>{x.partyName}</td><td>{x.partyGSTIN||'-'}</td><td>{x.hsn||'-'}</td><td>₹ {money(x.taxableAmount)}</td><td>₹ {money(x.cgst)}</td><td>₹ {money(x.sgst)}</td><td>₹ {money(x.igst)}</td></tr>)}</tbody></table></div></>:<div className="muted">Loading GST report...</div>}</div>}
</main>}
