import React,{useEffect,useMemo,useState} from "react";
import {hrApi} from "../lib/hrApi.js";
const money=n=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
export default function PayrollReport(){
 const now=new Date(),[month,setMonth]=useState(now.getMonth()+1),[year,setYear]=useState(now.getFullYear()),[rows,setRows]=useState([]),[error,setError]=useState("");
 async function load(){try{const r=await hrApi.salaries(`?month=${month}&year=${year}`);setRows(r.salaries||[])}catch(e){setError(e.message)}} useEffect(()=>{load()},[month,year]);
 const total=useMemo(()=>rows.reduce((a,x)=>({...a,ot:a.ot+Number(x.overtimeAmount||0),cut:a.cut+Number(x.cuttingAmount||0),gross:a.gross+Number(x.grossSalary||0),net:a.net+Number(x.netSalary||0)}),{ot:0,cut:0,gross:0,net:0}),[rows]);
 return <main style={S.page}><div style={S.wrap}><header style={S.head}><div><h1>Payroll Report</h1><p>Approved overtime and cutting reflected in salary.</p></div><div><select style={S.input} value={month} onChange={e=>setMonth(e.target.value)}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(2000,i,1).toLocaleString("en-IN",{month:"long"})}</option>)}</select><input style={S.input} type="number" value={year} onChange={e=>setYear(e.target.value)}/></div></header>{error&&<div style={S.err}>{error}</div>}
 <div style={S.cards}><div><b>{rows.length}</b><span>Employees</span></div><div><b>{total.ot.toFixed(2)}</b><span>Approved OT Amount</span></div><div><b>{money(total.cut)}</b><span>Cutting Deduction</span></div><div><b>{money(total.net)}</b><span>Net Payable</span></div></div>
 <section style={S.table}><div style={S.th}><span>Employee</span><span>Present</span><span>OT Hours</span><span>OT Amount</span><span>Cutting</span><span>Cutting Amount</span><span>Gross</span><span>Net Payable</span></div>{rows.map(x=><div style={S.tr} key={x._id}><span><b>{x.employeeId?.name||"-"}</b><small>{x.employeeId?.employeeCode||""}</small></span><span>{x.presentDays||0}</span><span>{Number(x.overtimeHours||0).toFixed(2)} h</span><span>{money(x.overtimeAmount)}</span><span>{Math.floor(Number(x.cuttingMinutes||0)/60)}h {Number(x.cuttingMinutes||0)%60}m</span><span>{money(x.cuttingAmount)}</span><span>{money(x.grossSalary)}</span><strong>{money(x.netSalary)}</strong></div>)}</section></div></main>
}
const S={page:{minHeight:"100vh",background:"#f5f7fb",padding:24,fontFamily:"Arial"},wrap:{maxWidth:1400,margin:"0 auto"},head:{display:"flex",justifyContent:"space-between",alignItems:"center"},input:{padding:11,border:"1px solid #d0d5dd",borderRadius:9,marginLeft:7},err:{background:"#fee4e2",color:"#b42318",padding:12,borderRadius:10},cards:{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,margin:"20px 0"},table:{background:"#fff",borderRadius:14,overflow:"hidden"},th:{display:"grid",gridTemplateColumns:"1.5fr .6fr .8fr 1fr 1fr 1fr 1fr 1fr",gap:10,padding:14,background:"#eef2f7",fontWeight:700},tr:{display:"grid",gridTemplateColumns:"1.5fr .6fr .8fr 1fr 1fr 1fr 1fr 1fr",gap:10,padding:14,borderTop:"1px solid #eef2f7",alignItems:"center"}};
