import React,{useEffect,useState} from "react";
import {hrApi} from "../lib/hrApi.js";

export default function Salary(){
 const now=new Date(),[employees,setEmployees]=useState([]),[rows,setRows]=useState([]),[form,setForm]=useState({employeeId:"",month:now.getMonth()+1,year:now.getFullYear(),bonus:0,deductions:0,overtimeRate:""}),[error,setError]=useState("");
 async function load(){try{const[e,s]=await Promise.all([hrApi.employees(),hrApi.salaries()]);setEmployees(e.employees||[]);setRows(s.salaries||[]);if(!form.employeeId&&e.employees?.[0])setForm(f=>({...f,employeeId:e.employees[0]._id}))}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[]);
 async function generate(e){e.preventDefault();try{await hrApi.generateSalary({...form,month:Number(form.month),year:Number(form.year),bonus:Number(form.bonus||0),deductions:Number(form.deductions||0),overtimeRate:form.overtimeRate?Number(form.overtimeRate):undefined});load()}catch(e){setError(e.message)}}
 return <main style={S.page}><h1>Salary & Payroll</h1><p style={S.sub}>Attendance-based salary with overtime, bonus and deductions</p>{error&&<p style={S.error}>{error}</p>}
 <form onSubmit={generate} style={S.card}><select style={S.input} value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}>{employees.map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select><input type="number" min="1" max="12" style={S.input} value={form.month} onChange={e=>setForm({...form,month:e.target.value})}/><input type="number" style={S.input} value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/><input type="number" placeholder="Bonus" style={S.input} value={form.bonus} onChange={e=>setForm({...form,bonus:e.target.value})}/><input type="number" placeholder="Manual deductions" style={S.input} value={form.deductions} onChange={e=>setForm({...form,deductions:e.target.value})}/><input type="number" placeholder="OT rate/hour optional" style={S.input} value={form.overtimeRate} onChange={e=>setForm({...form,overtimeRate:e.target.value})}/><button style={S.btn}>Generate / Recalculate</button></form>
 <section style={S.card}>{rows.map(x=><div key={x._id} style={S.row}><b>{x.employeeId?.name}<small>{x.month}/{x.year}</small></b><span>Present {x.presentDays}</span><span>Absent {x.absentDays}</span><span>Gross ₹{Number(x.grossSalary||0).toLocaleString("en-IN")}</span><strong>Net ₹{Number(x.netSalary||0).toLocaleString("en-IN")}</strong><button style={S.slip} onClick={async()=>{const d=await hrApi.salarySlip(x._id);alert(`Salary Slip\n${d.salary.employeeId.name}\nNet Salary: ₹${Number(d.salary.netSalary).toLocaleString("en-IN")}`)}}>View Slip</button></div>)}</section></main>
}
const S={page:{padding:24,background:"#f5f7fb",minHeight:"100vh",fontFamily:"Arial"},sub:{color:"#667085"},card:{background:"#fff",padding:20,borderRadius:18,marginTop:18,boxShadow:"0 8px 24px rgba(15,23,42,.06)"},input:{padding:12,border:"1px solid #d9e1ec",borderRadius:10,margin:5},btn:{padding:"12px 18px",background:"#1d4f91",color:"#fff",border:0,borderRadius:10,fontWeight:700},row:{display:"grid",gridTemplateColumns:"1.4fr .8fr .7fr 1fr 1fr .7fr",gap:10,padding:"14px 0",borderBottom:"1px solid #eee",alignItems:"center"},slip:{border:0,borderRadius:8,padding:"8px 10px",background:"#edf4ff",color:"#1d4f91"},error:{background:"#fee4e2",color:"#b42318",padding:10,borderRadius:10}};
